apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: ducksnest-vxlan
spec:
  cidr: 10.244.0.0/16
  vxlanMode: Always
  ipipMode: Never
  natOutgoing: true
  disabled: false
  blockSize: 26
  nodeSelector: all()
