apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: ducksnest-crosssubnet-pool
spec:
  cidr: 10.244.0.0/16
  vxlanMode: CrossSubnet
  ipipMode: Never
  natOutgoing: true
  disabled: false
  blockSize: 26
  nodeSelector: all()