apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: ducksnest-lan-pool
spec:
  cidr: 10.244.0.0/16
  vxlanMode: Never
  ipipMode: Always
  natOutgoing: true
  disabled: false
  blockSize: 26
  nodeSelector: all()